spring.application.name=user
server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=${RMQ_ADDRESS}
broker.queue.email.name=${RMQ_QUEUE}

